# Your Name or Company
title: 사미굴리나 마리아

# Description of your website. This is used for social sharing.
description:  202218022 사미굴리나 마리아 입니다. 

# A brief blurb about yourself
content: 글로벌자율전공학부 컴퓨터공학전공 2학년 학생입니다. 

# Add your social links
social:
  - platform: github
    url: https://github.com/samigumar
#  - platform: facebook
#    url: https://facebook.com/brianmaierjr
#  - platform: twitter
#    url: https://twitter.com/brianmaierjr
#  - platform: linkedin
#    url: brianmaierjr

# General settings
# url: http://brianmaierjr.github.com/uni
# baseurl: "/uni" 
#markdown: kramdown
sharing_image: my_dog_maru.jpg
google_analytics: "UA-58263416-1" # google analytics tracking

#### LAYOUT OPTIONS #####

# Half layout
half_side: right

# Full layout
full_text_position: right # left, right or center
